### ISSUE TITLE
Change license or add exceptions to your ARR licensing

### ISSUE THREAD

**Issue by PaintNinja** [GiantLuigi4/Better_FPS_Graph#1]
I would like to use this mod in modpacks and use its API in some existing mods, however the All Rights Reserved license on CurseForge prohibits this.

Could you consider changing the license to something more permissive like MIT, BSD, etc or adding exceptions to your license that explicitly state that use of this mod is permitted in modpacks and/or for using its API?

**Comment by GiantLuigi4** [comment]
I... tend to just leave it as default.
I’ll do this on pc.

**Comment by GiantLuigi4** [comment]
I... tend to just leave it as default.
I’ll do this on pc.

**Comment by GiantLuigi4** [comment]
I... tend to just leave it as default.
I’ll do this on pc.

**Comment by GiantLuigi4** [comment]
I... tend to just leave it as default.
I’ll do this on pc.

**Comment by GiantLuigi4** [comment]
I... tend to just leave it as default.
I’ll do this on pc.

**Comment by GiantLuigi4** [comment]
I... tend to just leave it as default.
I’ll do this on pc.

**Comment by GiantLuigi4** [comment]
I... tend to just leave it as default.
I’ll do this on pc.

**Comment by GiantLuigi4** [comment]
Shoot.
I commented like 8 times. 
Uhh.

**Comment by GiantLuigi4** [comment]
Ok, done.
